name: CI/CD Pipeline - Infraestructura UPB

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Desplegar en AWS Academy
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: 🛎️ Clonar el repositorio
        uses: actions/checkout@v4

      - name: ⚙️ Configurar credenciales de AWS (Sandbox)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      # --- NUEVO PASO: BOOTSTRAPPING DEL BUCKET S3 ---
      - name: 🪣 Preparar Bucket S3 para Terraform State
        run: |
          BUCKET_NAME="upb-parcial-backend-terraform-bryan"
          
          # AWS CLI pregunta silenciosamente si el bucket ya existe
          if ! aws s3api head-bucket --bucket $BUCKET_NAME 2>/dev/null; then
            echo "El bucket no existe. Creando infraestructura de estado..."
            aws s3 mb s3://$BUCKET_NAME --region us-east-1
          else
            echo "El bucket ya existe. Procediendo con Terraform..."
          fi
      # -----------------------------------------------

      - name: 🏗️ Configurar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: 🚀 Inicializar Terraform
        run: terraform init

      - name: 🔍 Validar y Planificar
        run: terraform plan -out=tfplan

      - name: ✅ Aplicar Cambios Automáticamente
        run: terraform apply -auto-approve tfplan